### ISSUE TITLE
Не привильный список стадий

### ISSUE THREAD

**Issue by taraswww777** [taraswww777/sky-trainer#117]
у нас не такой список стадий, вот список подтягивается по апи в приложении

![Image](https://user-images.githubusercontent.com/13847428/225322158-81b7cdc7-f1f0-47c2-9ec3-e1922414b3ac.jpg)

**Comment by vanek1109** [comment]
вот скорее всего показано какие активированы, какие нет https://yadi.sk/d/oYWtofIob0IbbA

**Comment by taraswww777** [comment]
KPI лишний. по идее список должен откуда-то подтягиваться. 
по идее информация должна быть в сведениях по курсе
