### ISSUE TITLE
Какието проблемы с авторизацией

### ISSUE THREAD

**Issue by taraswww777** [taraswww777/sky-trainer#98]

**Comment by vanek1109** [comment]
Вот по шагам как сейчас это происходит:

1. По умолчанию у нас редирект на страницу https://nota.neurolab.systems/#/auth/login

2. Входим первый раз, при клике на кнопку Войти у нас просто происходит еще один редирект уже на https://nota.neurolab.systems/?#/auth/login - добавляется знак вопроса в адресе

3. Входим второй раз уже с нового адреса и заходит нормально
